M48
; DRILL file {KiCad 8.0.4} date 2024-11-14T12:54:45+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-14T12:54:45+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.1724Y-4.212
X4.1724Y-4.527
T2
X4.0984Y-2.4488
X4.0984Y-2.622
M30
